BeHapi.Web/Models/ErrorViewModel.cs
using System;

namespace BeHapi.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BeHapi.Web/Models/Products.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BeHapi.Web.Models
{
    public class Products
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Category { get; set; }
        public string PhysicalAddress { get; set; }
        public string LocationPath { get; set; }
    }
}

BeHapi.Web/Controllers/HomeController.cs
using BeHapi.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BeHapi.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BeHapi.Web/Controllers/HotelSearchController.cs
using BeHapi.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using BeHapi.Web.BusinessLayer;

namespace BeHapi.Web.Controllers
{
    public class HotelSearchController : Controller
    {
        // GET: HotelSearchController
        public ActionResult Index()
        {
            string msg = string.Empty;
            List<Products> productData = new List<Products>();

            HotelSearchBL hotelSearchBLObj = new HotelSearchBL();
            (productData,msg) = hotelSearchBLObj.FindByName();


            return View(productData);
        }

        [HttpPost]
        public ActionResult Index(string HotelName)
        {
            string msg = string.Empty;
            List<Products> productData = new List<Products>();

            HotelSearchBL hotelSearchBLObj = new HotelSearchBL();
            (productData, msg) = hotelSearchBLObj.FindByName(HotelName);

            return View(productData);
        }
    }
}

BeHapi.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BeHapi.Web/Views/HotelSearch/Index.cshtml
@model List<Products>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    @using (Html.BeginForm("Index", "HotelSearch", FormMethod.Post))
    {
        <span>Hotel Name:</span> @Html.TextBox("HotelName")
        <input type="submit" value="Search" />
        <br />
        <br />
        <table class ="table table-bordered table-condensed table-striped table-hover sortable">
            <tr>
                <th>ID</th>
                <th>Name</th>
                @*<th>Category</th>*@
                <th>PhysicalAddress</th>
                <th>Description</th>
                @*<th>LocationPath</th>*@
            </tr>
            @foreach (Products product in Model)
            {
        <tr>
            <td>@product.Id</td>
            <td>@product.Name</td>
            @*<td>@product.Category</td>*@
            <td>@product.PhysicalAddress</td>
            <td>@product.Description</td>
            @*<td>@product.LocationPath</td>*@
        </tr>
            }
            </table>
        }
</body>
</html>

BeHapi.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeHapi.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BeHapi.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HotelSearch" asp-action="Index">Hotel Search</a>
                        </li>
                        <!--<li class="nav-item">
                            <-->@*a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
                        <!--</li>-->
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BeHapi.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>